version: "3.9"
services:
    nvidia-license-server:
        build: .
        # these are required for systemd
        privileged: true
        volumes:
            - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
            - 'flexnetls:/var/opt/flexnetls'
        ports:
            - "${WEB_UI_PORT}:8080"
            - "${LICENSE_PORT}:7070"
        mac_address: "${MAC_ADDRESS}" # Registered with NVIDIA
        hostname: "${HOSTNAME}"
        restart: always
volumes:
        flexnetls:

